version: 2.1

jobs:
  build2:
    docker:
      - image: cimg/go:1.18.3-node
    working_directory: ~/xws-project/post-service
    steps:
      - checkout:
          path: ~/xws-project
      - run:
          name: Install dependencies and build project
          command: go version
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build2:
          filters:
            branches:
              only:
                - security
          context: SonarCloud2
